# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f85f4c8cf13e38bf041b0bfa184e858e1178656120dc99d448470086d1ea1de770efd823ecf00463aaf9a1a0f68aa9fae06f459883461d3dbaf7b5d9fa58c51a

test:
  secret_key_base: 47474e363aa8924bf3aa632cf09870d5419d17e31c790accfa3282e523a90c8faa309ea58724f18094a1330a665bcb00135fe4c61b4c1d02eb889cfeb791c22a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
